openapi: 3.0.1
info:
  title: API de Consultoras
  version: "1.0"
servers:
  - url: https://oo9g5hp6y7.execute-api.us-east-1.amazonaws.com/dev
paths:
  /consultoras/{codpais}:
    get:
      summary: Obtiene informaci칩n de consultoras
      operationId: getConsultans
      parameters:
        - name: codpais
          in: path
          required: true
          schema:
            type: string
        - name: rows
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Operaci칩n exitosa
        '400':
          description: Petici칩n inv치lida